version: '2'

services:
  fuel_app:
    container_name: "fuel_app"
    build: ./app
    restart: always
    env_file: ./app/env
    links:
      - fuel_mysql:db
    volumes:
      - /var/run
      - ./yogatribes-api:/usr/src/api
      - ./yogatribes:/usr/src/app

  fuel_nginx:
    container_name: "fuel_nginx"
    build: ./nginx
    restart: always
    links:
      - fuel_mysql:db
    ports:
      - "3001:3001"
      - "3002:3002"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/application.conf:/etc/nginx/conf.d/application.conf
    volumes_from:
      - fuel_app

  fuel_mysql:
    container_name: "fuel_mysql"
    image: mysql:5.7.24
    restart: always
    command: --max_allowed_packet=32505856
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
    ports:
      - "3306:3306"


